### ISSUE TITLE
1.7.1 release?

### ISSUE THREAD

**Issue by copumpkin** [gnustep/libobjc2#1]
I'm running into the same issue as described in [here](https://lists.gnu.org/archive/html/discuss-gnustep/2013-12/msg00221.html). A poster (David Chisnall) says he'll release 1.7.1 soon, but that was over a year ago and the latest version linked from gnustep.org is still 1.7. Is the newer release just poorly advertised?

Also, would it be possible to add git tags corresponding to releases?

**Comment by crontab** [comment]
Are you compiling it in MinGW? Do you use my fork or the original?

**Comment by davidchisnall** [comment]
I've now recreated the git repo on GitHub using svn2git, so it correctly mirrors all of the releases.  I hope to do a 1.8 release from trunk this week, as there are a number of unreleased changes.

**Comment by vincentwoo** [comment]
@davidchisnall Did this ever happen? I'm having a ton of problems building libobjc2 under clang 3.5 (I can get it to work under 3.4).

**Comment by davidchisnall** [comment]
Not yet.  I've just pushed out the current git head to FreeBSD ports and want to give it a little bit of wider testing before an official release.

**Comment by vincentwoo** [comment]
Roger that. I'm building off your fork now and that seems to do the trick!

**Comment by davidchisnall** [comment]
https://github.com/gnustep/libobjc2/releases/tag/v1.8
