### ISSUE TITLE
Too much space reserved for isa pointers in root classes

### ISSUE THREAD

**Issue by SSheldon** [gnustep/libobjc2#10]
When creating a root class, it looks like `sizeof(struct objc_class)` is used rather than `sizeof(struct objc_class *)` [in runtime.c](https://github.com/gnustep/libobjc2/blob/d3bcc30/runtime.c#L727-L730). This results in enough space being reserved for a full class to be stored inline in each instance, rather than just enough space for a pointer to one; 144 bytes in my testing.

I think the fix should be just:
``` diff
diff --git a/runtime.c b/runtime.c
index 4352ccc..426a0d8 100644
--- a/runtime.c
+++ b/runtime.c
@@ -726,7 +726,7 @@ Class objc_allocateClassPair(Class superclass, const char *name, size_t extraByt
 
        if (Nil == superclass)
        {
-               newClass->instance_size = sizeof(struct objc_class);
+               newClass->instance_size = sizeof(struct objc_class *);
        }
        else
        {
```

But I haven't tested that. Hope this helps! :)

**Comment by davidchisnall** [comment]
Ooops, forgot to fix in the commit message.  Fixed in 53bc9f3.
