### ISSUE TITLE
Block types used for imp_implementationWithBlock() and imp_getBlock()

### ISSUE THREAD

**Issue by rupertdaniel** [gnustep/libobjc2#103]
I have a query on the types used to represent blocks for the functions:
```
IMP imp_implementationWithBlock(void *block);
char *block_copyIMPTypeEncoding_np(void*block);
void *imp_getBlock(IMP anImp);
```
libobjc2 uses the type `void *`, but the Apple runtime uses `id`. 

Also libobjc2 already uses `id` for `id objc_retainBlock(id b)`.

I was just wandering if there is reason why `void *` is used for these functions in libobjc2?

**Comment by davidchisnall** [comment]
Apple used `void*` when they introduced these functions.  I presume that they changed to `id` for better interop with ARC.  I'm happy to accept a PR that changes them.
