### ISSUE TITLE
libobjc2-2.0/objc/slot.h:26:38: error: expected initializer before ‘objc_method_cache_version’

### ISSUE THREAD

**Issue by abraovic** [gnustep/libobjc2#118]
Hi,

I'm trying to install release [v2.0](https://github.com/gnustep/libobjc2/archive/v2.0.tar.gz), but I've stuck with this error. 

System is Ubuntu 18.04 (EC2 amazon instance). On top of that here is a list of software installed: 

- build-essential
- clang
- libblocksruntime-dev
- libkqueue-dev
- libpthread-workqueue-dev
- gobjc
- libxml2-dev
- libjpeg-dev
- libtiff-dev
- libpng-dev
- libcups2-dev
- libfreetype6-dev
- libcairo2-dev
- libxt-dev 
- libgl1-mesa-dev
- cmake

Also, `libdispatch-dev` is removed (it was not installed anyways since this is a _fresh instance_)

After downloading and unpacking the archive here are my command line inputs:
```
export CC=clang
mkdir Build
cd Build
cmake ..
make -j8
```

I have followed instructions from [INSTALL](https://github.com/gnustep/libobjc2/blob/9d790b411848956ec35c8b334e20178b6b15e58b/INSTALL) file, and from [here](https://blog.tlensing.org/2013/02/24/objective-c-on-linux-setting-up-gnustep-clang-llvm-objective-c-2-0-blocks-runtime-gcd-on-ubuntu-12-04/#comment-54284).

Error log:
```
In file included from /root/gnustep-dev/libobjc2-2.0/objc/runtime.h:219:0,
                 from /root/gnustep-dev/libobjc2-2.0/objcxx_eh.cc:6:
/root/gnustep-dev/libobjc2-2.0/objc/slot.h:26:38: error: expected initializer before ‘objc_method_cache_version’
 OBJC_PUBLIC extern _Atomic(uint64_t) objc_method_cache_version;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/objc.dir/build.make:742: recipe for target 'CMakeFiles/objc.dir/objcxx_eh.cc.o' failed
make[2]: *** [CMakeFiles/objc.dir/objcxx_eh.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/objc.dir/all' failed
make[1]: *** [CMakeFiles/objc.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

Attached complete console output for `cmake ..` and `make -j8`
[cmake.txt](https://github.com/gnustep/libobjc2/files/3396180/cmake.txt)
[make.txt](https://github.com/gnustep/libobjc2/files/3396181/make.txt)

**Comment by davidchisnall** [comment]
This line is suspicious in your CMake output:

```
-- The CXX compiler identification is GNU 7.4.0
```

It appears as if you're trying to compile the [Objective-]C++ with gcc, not clang.  You need to set `CMAKE_CXX_COMPILER` to a compiler that understands C11.

This is also a bit worrying:

```
-- The C compiler identification is Clang 6.0.0
```

Clang 6 does not support the 2.x ABI.  7.0 is the minimum and 8.x is recommended for the 2.0 release.
