### ISSUE TITLE
objc_storeWeak on a block encounters an access violation

### ISSUE THREAD

**Issue by DHowett-MSFT** [gnustep/libobjc2#12]
I'm seeing an access violation in the ARC reference counting fast path for blocks.
We end up reading `sizeof(uintptr_t)` bytes before the beginning of a block instance before the fast_arc flag check on isa here: https://github.com/gnustep/libobjc2/blob/master/arc.m#L528

**Comment by davidchisnall** [comment]
Thanks for the report.  I also found another bug while chasing this one.  Both are now fixed.
