### ISSUE TITLE
Instructions in INSTAll don't work to build current version

### ISSUE THREAD

**Issue by rfm** [gnustep/libobjc2#139]
The problem after running cmake, at the make stage, is:

/home/richard/git/libobjc2/arc.mm:6:10: fatal error: 
      'third_party/robin-map/include/tsl/robin_map.h' file not found
#include "third_party/robin-map/include/tsl/robin_map.h"

While anyone really determined will work out, after a while, that this is due to a missing dependency that needs to be found and installed, it really shouldn't be necessary.  The cmake/make process should handle all that seamlessly.  Is there perhaps some way for git to manage it so that the required third party project is always available as part of the libobjc2 project (ie if libobjc2 is cloned or downloaded from github as a zip file, the robin-map code would be part of it)?

**Comment by davidchisnall** [comment]
You appear not to have checked out the submodules.  Did you clone with `git clone --recursive`?  If not, then you will need to run the `git submodule` commands to pull in the submodules.

**Comment by rfm** [comment]
> On 15 Dec 2019, at 11:15, David Chisnall <notifications@github.com> wrote:
> 
> You appear not to have checked out the submodules. Did you clone with git clone --recursive? If not, then you will need to run the git submodule commands to pull in the submodules.

Well that would be because I didn't know about those commands/options or that I needed to).

The issue is not that I couldn't find what I needed eventually, but that I should't need to *fight* to be able to build/install things, and that the INSTALL instructions should be complete/accurate.
Basically, if you go to the project on GitHub, and follow the normal instructions to clone or download a zip archive, the INSTALL instructions simply won't work.

**Comment by davidchisnall** [comment]
You just need to follow the normal steps for cloning a git project that has submodules.  The install instructions cover how to build the code, they assume that you've already successfully acquired it.

**Comment by rfm** [comment]
> On 15 Dec 2019, at 16:52, David Chisnall <notifications@github.com> wrote:
> 
> You just need to follow the normal steps for cloning a git project that has submodules. 

I think the problem is this notion of 'normal' steps(or the notion that people know about submodules).

If you go to the project on GitHub the only instruction for getting the source is the 'Clone or download' menu, which gives you a URL to use or a button to download a zip archive.  So GitHub seems to disagree with you about what's 'normal'.

Of course, we might say to people "Don't use GitHub",  and put a copy on the GNUstep ftp server, if we don't want them to have a hard time finding they've only got part of the required source.

**Comment by ngrewe** [comment]
I quite agree with Richard: It is not very well discoverable that libobjc2 now is a "project that has submodules". A simple git checkout of the clone URL displayed on github will not give any indication that you're missing the submodule (at least not with the git configuration on any machine that I own).

**Comment by davidchisnall** [comment]
I'm happy to take a PR that documents this, but given the prevalence of submodules and the fact that this is a pretty common git workflow, I'm surprised that it's causing problems.
