### ISSUE TITLE
Faulty pgk-config  file installed on gnustep systems

### ISSUE THREAD

**Issue by rfm** [gnustep/libobjc2#140]
On a gnustep system, the installation location is detected using gnustep-config.
The problem is that, while the library is correctly installed in that location (and the libobjc.pc file is installed in the correct location), the content of that file is incorrect and causes anything depending on pkg-config for information about libobjc to fail.

For example my libobjc.pc has a prefix of /usr/local but the gnustep installation is in /home/richard/gnustep-ng.
My libobjc.pc looks like this:

prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}//home/richard/gnustep-ng/Local/Library/Libraries
includedir=${prefix}//home/richard/gnustep-ng/Local/Library/Headers

Name: libobjc
Description: GNUstep Objective-C runtime library
Version: 2.0.0

Cflags: -I${includedir}
Libs: -L${libdir} -lobjc

I presume cmake generates this somehow (I hoave no idea how to configure that), and needs to either use a different template or perhaps be aware that 'prefix s '/' rather than '/usr/local'

**Comment by davidchisnall** [comment]
Assigning to @ngrewe, who contributed the pkg-config support.

**Comment by ngrewe** [comment]
Thanks for the report Richard!  I'm afraid I missed the fact that under gnustep-make we'd have absolute directories for `LIB_INSTALL_PATH` and `HEADER_INSTALL_PATH`. I've fixed this by setting the prefix to `/` as you suggested.

**Comment by rfm** [comment]
> On 15 Dec 2019, at 12:45, Niels Grewe <notifications@github.com> wrote:
> 
> Thanks for the report Richard! I'm afraid I missed the fact that under gnustep-make we'd have absolute directories for LIB_INSTALL_PATH and HEADER_INSTALL_PATH. I've fixed this by setting the prefix to / as you suggested.

Thanks ... that works for me.
