### ISSUE TITLE
Error:/usr/local/include/ObjectiveC2/objc/runtime.h:146:1: error: unknown type name 'Method_t'; did you mean 'Method'?

### ISSUE THREAD

**Issue by pangdahua** [gnustep/libobjc2#16]
/usr/local/include/ObjectiveC2/objc/runtime.h:146:1: error: unknown type name 'Method_t'; did you mean 'Method'?

Centos

command:
clang -fblocks -fobjc-nonfragile-abi main.m -o main

**Comment by davidchisnall** [comment]
I think that you have filed this bug in the wrong place.  If you have ObjectiveC2 headers then you are using GNUstep-base's compatibility layer for old versions of the GCC Objective-C runtime.  This should not be used with libobjc2.  If you *are* using libobjc2, then you have misconfigured GNUstep-base.
