### ISSUE TITLE
Can't link certain programs with libobjc: undefined reference: eh_trampoline()

### ISSUE THREAD

**Issue by zeising** [gnustep/libobjc2#177]
Hi!
After updating the FreeBSD port of libobjc2 to the latest version, specific programs such as gnustep-back, can no longer link with libobjc2.  I get the error 
```
/usr/local/bin/ld.bfd: /usr/local/lib/libobjc.so: undefined reference to `eh_trampoline()'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
see http://package18.nyi.freebsd.org/data/121amd64-default-PR244494/2020-08-25_21h45m10s/logs/errors/gnustep-back-0.27.0.log for more details.

I'm unsure about the cause of this. eh_trampoline() is declared as hidden, maybe it shouldn't be? I can't rule out it's specific compiler flags in either the build of libobjc2 or gnustep-back that's the problem, but I'm unfamiliar with gnustep in general and would muc appreciate some guidance.
Thank you!

**Comment by davidchisnall** [comment]
It should be declared as hidden (that means that it isn't exposed from the .so, but that's what we want).  

This is a weird compilation chain, because we use the compiler to generate assembly from a C++ source, but then replace the personality function in the assembly, then assemble and link that.

Do you have the build log for libobjc2?  We should probably enable the test suite there: we have CI for FreeBSD, so I suspect it's a problem in the flags that we're passing to the build in the libobjc2 port.

**Comment by zeising** [comment]
http://package18.nyi.freebsd.org/data/121amd64-default-PR244494/2020-08-25_21h45m10s/logs/libobjc2-2.1_1.log is the build log of libobjc2 (from the same builder).

When I updated libobjc2 I simply bumped the version and added the needed dependency on robin-map.

You can see the current FreeBSD ports version, and how it is built, here https://github.com/freebsd/freebsd-ports/tree/master/lang/libobjc2

I can run the test suite in a build jail from the ports version, but probably not before tomorrow.

**Comment by zeising** [comment]
I managed to get the test suite running in a poudriere build jail with a FreeBSD 12.1 userland on a FreeBSD 13 kernel.  There were several errors in the test suite, so there might be issues in how FreeBSD ports builds things:
```
78% tests passed, 40 tests failed out of 186

Total Test time (real) =   9.75 sec

The following tests FAILED:
         41 - ExceptionTest (Failed)
         42 - ExceptionTest_optimised (Failed)
         43 - ExceptionTest_legacy (Failed)
         44 - ExceptionTest_legacy_optimised (Failed)
         57 - NestedExceptions (Failed)
         58 - NestedExceptions_optimised (Failed)
         59 - NestedExceptions_legacy (Failed)
         60 - NestedExceptions_legacy_optimised (Failed)
         85 - RuntimeTest (Failed)
         86 - RuntimeTest_optimised (Failed)
         87 - RuntimeTest_legacy (Failed)
         88 - RuntimeTest_legacy_optimised (Failed)
        125 - objc_msgSend (Failed)
        126 - objc_msgSend_optimised (Failed)
        127 - objc_msgSend_legacy (Failed)
        128 - objc_msgSend_legacy_optimised (Failed)
        133 - NilException (Failed)
        134 - NilException_optimised (Failed)
        135 - NilException_legacy (Failed)
        136 - NilException_legacy_optimised (Failed)
        161 - BoxedForeignException (Failed)
        162 - BoxedForeignException_optimised (Failed)
        163 - BoxedForeignException_legacy (Failed)
        164 - BoxedForeignException_legacy_optimised (Failed)
        165 - ForeignException (Failed)
        166 - ForeignException_optimised (Failed)
        167 - ForeignException_legacy (Failed)
        168 - ForeignException_legacy_optimised (Failed)
        171 - CXXExceptions (Failed)
        172 - CXXExceptions_optimised (Failed)
        173 - CXXExceptions_legacy (Failed)
        174 - CXXExceptions_legacy_optimised (Failed)
        179 - ObjCXXEHInterop (Failed)
        180 - ObjCXXEHInterop_optimised (Failed)
        181 - ObjCXXEHInterop_legacy (Failed)
        182 - ObjCXXEHInterop_legacy_optimised (Failed)
        183 - ObjCXXEHInterop_arc (Failed)
        184 - ObjCXXEHInterop_arc_optimised (Failed)
        185 - ObjCXXEHInterop_arc_legacy (Failed)
        186 - ObjCXXEHInterop_arc_legacy_optimised (Failed)
```

**Comment by zeising** [comment]
When running the build manually, just with cmake; ninja, ctest -j4, using the system compiler, things are working fine and tests pass.

**Comment by davidchisnall** [comment]
Very odd.  The ports Makefile looks as if it's not doing anything odd.  Can you see the cmake invocation?  It didn't seem to be in the log.

**Comment by zeising** [comment]
I'll see about digging out the cmake invocation. I'm not super used to cmake and how it works in the FreeBSD ports system. However, I noticed something else, eh_trampoline.s is empty when doing the ports build, but not when building manually.
I wonder if this is the culprit, from the build log:
```
[1/424] cd /wrkdirs/usr/ports/lang/libobjc2/work/.build && /usr/bin/c++ -O2\ -pipe\ -fno-strict-aliasing -fPIC -S /wrkdirs/usr/ports/lang/libobjc2/work/libobjc2-2.1/eh_trampoline.cc -o - -fexceptions -fno-inline | sed s/__gxx_personality_v0/test_eh_personality/g > /wrkdirs/usr/ports/lang/libobjc2/work/.build/eh_trampoline.s
error: invalid integral value '2 -pipe -fno-strict-aliasing' in '-O2 -pipe -fno-strict-aliasing'
error: invalid integral value '2 -pipe -fno-strict-aliasing' in '-O2 -pipe -fno-strict-aliasing'
```
The FreeBSD ports system adds -O2 -pipe -fno-strict-aliasing to CFLAGS by default.

**Comment by zeising** [comment]
Here is the command line invocation:
```
cd /wrkdirs/usr/ports/lang/libobjc2/work/.build; /usr/bin/env OBJC="cc" OBJCFLAGS=" -O2 -pipe  -fno-strict-aliasing  -Wno-import" XDG_DATA_HOME=/wrkdirs/usr/ports/lang/libobjc2/work  XDG_CONFIG_HOME=/wrkdirs/usr/ports/lang/libobjc2/work  HOME=/wrkdirs/usr/ports/lang/libobjc2/work TMPDIR="/tmp" PATH=/wrkdirs/usr/ports/lang/libobjc2/work/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/nonexistent/bin SHELL=/bin/sh CONFIG_SHELL=/bin/sh /usr/local/bin/cmake -DLIB_INSTALL_PATH=lib -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-strict-aliasing  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -GNinja /wrkdirs/usr/ports/lang/libobjc2/work/libobjc2-2.1
```

**Comment by davidchisnall** [comment]
A Release build  (`-DCMAKE_BUILD_TYPE=Release`) should be doing `-O2`.  `-pipe` is ignored by clang, and it's probably the default for GCC now (it just means use a pipe between the compiler and assembler instead of a temporary file, which doesn't do anything in clang where they're the same process).  `-fno-strict-aliasing` shouldn't make a difference for anything with respect to function visibility.  

That said, I can now reproduce this.  When I configure the build with:

```
$  cmake .. -DLIB_INSTALL_PATH=lib -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-strict-aliasing  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -GNinja
```

I see the same failures.  Now to figure out which of those options is causing it.  Some of them are clearly no-ops (e.g. the ones that relate to generating Makefiles with colour output, which are ignored since we're using the Ninja generator)...

**Comment by zeising** [comment]
-O2 -pipe -fno-strict-aliasing are used for all builds regardless of build system, so even if they're noops with cmake they might be hard to get out of the ports system.  The color stuff is probably because not everything in ports using cmake is also using ninja.
In any case, I have a hard time seeing why they should affect things (-O2 could affect code gen in this case, I guess).

Thank you very much for your help so far!  Let me know if I can provide anything else!

**Comment by davidchisnall** [comment]
See #178

**Comment by zeising** [comment]
The FreeBSD port of libobjc2 has been updated with the patch.  Thank you very very much for your help and fix!
