### ISSUE TITLE
Result of ivar_getTypeEncoding only contains one character for object-valued ivars under clang on Linux

### ISSUE THREAD

**Issue by dlobron** [gnustep/libobjc2#19]
I recently compiled an Objective-C program on Linux using clang/llvm .  I'm using libobjc2-1.8.1, with llvm 3.7.  My program links with a shared library (also written in ObjC), which introspects the instance variables in a common Configuration class to determine what type each of those variables is.  This has always worked on the Mac with clang and on Linux with gcc.  However, with clang/llvm on Linux, I'm finding that the type introspection fails.  The shared library code looks like this:

```
Ivar *ivarList = class_copyIvarList(c, &ivarCount);
for (i = 0; i < ivarCount; i++) {
   Ivar ivar = ivarList[i];
   const char *ivarCname = ivar_getName(ivar);
   if (ivarCname != 0 && ivarCname[0] != '_') {
        NSString *ivarName = [NSString stringWithUTF8String:ivarCname];
        const char *ivarType = ivar_getTypeEncoding(ivar);
        bool isObjectValuedIvar = (ivarType[0] == '@' && ivarType[1] == '"')
        if (isObjectValuedIvar) {
            NSString *className = [[[NSString alloc] initWithBytes: &ivarType[2]
                                            length: strlen(&ivarType[2])-1
                                        encoding: NSUTF8StringEncoding] autorelease];
           Class c = NSClassFromString(className);
```

I'm finding that the call to ivar_getTypeEncoding returns "@" in the ivarType variable.  However, that variable only contains "@".  It doesn't have any element 1 or 2, and my code seg faults when I try to access them.  I ran the code under gdb with optimization turned off, and verified that the ivarCname and ivarType variables contain the variable name and "@", respectively:

(gdb) print ivarCname
$9 = 0x4a4575 "sslCertificateFile"
(gdb) print ivarType
$5 = 0x4a5951 "@"

Should the call to ivar_getTypeEncoding be returning more than "@"? 

Another oddity here is that the ivar object itself seems opaque.  I can't seem to print the struct members:

(gdb) print ivar
$12 = (Ivar) 0x6e1160 <.objc_ivar_list+776>
(gdb) print ivar.name
There is no member named name.
(gdb) print ivar.type
There is no member named type.
(gdb) print ivar->type
There is no member named type.

I'm not sure how this is possible, because the ivar_getTypeEncoding function just does this:

```
const char * ivar_getTypeEncoding(Ivar ivar)
{
        CHECK_ARG(ivar);
        return ivar->type;
}
```

I'd appreciate any help here!  I'm wondering if my code is somehow finding different versions of the runtime - I'm not sure how I can determine that beyond using gdb.

**Comment by davidchisnall** [comment]
I'm surprised if this code worked with GCC on Linux.  A little while ago, Apple changed the ivar type encodings to be more verbose (to contain the class names as well as the fact that it was an object).  We didn't enable this for non-Apple platforms, because it broke some code that was parsing the type encodings (and became very unhappy with trailing characters).

If you need the class information, there's currently no way for you to get it (we'll need to flip the switch in clang to enable the more verbose information).  

I don't think this is a runtime bug, because the runtime is just returning the information that the compiler is generating.  If this is incompatible with OS X, then we probably should tweak clang to emit the more verbose type encoding.

Note that even on OS X your code looks broken.  If the type of the ivar is `id`, then the encoding will simply be `"@"` and so attempts to dereference index 2 are invalid.  If you handle this case correctly, and then you'll simply have a little bit less information here than on OS X.

For your debug issue, gdb is probably seeing the definition of the `Ivar` type from the compilation unit of the current stack frame, which is an opaque type.  If you cast it to a pointer to the struct that the runtime uses internally (and you've compiled the runtime in debug mode) then you should be able to print it.

**Comment by dlobron** [comment]
Thanks very much, David- that makes sense.  On further investigation, it looks like we were using the gnustep-base objc on top of the GCC runtime on Linux (not libobjc2), and that's why the introspection was working.  

You mentioned we could flip a switch in clang to get more verbose information.  Would you want me to try doing that, to see how it works?  Alternately, could I modify libobjc2 to include the class name, the way gnustep-base appears to do?  I realize this might be risky, and if other users are not doing this kind of type introspection I don't want to risk breaking things for them - I can try to change the way our introspection works.

**Comment by davidchisnall** [comment]
I don't think changing the runtime will help.  The runtime can only provide information that's left by the compiler here.  It can't synthesize it from anywhere else (though you can use introspection on the value to find what the class of the current object is).  If you compile with GCC, does it provide extra information in the type encoding?  If so, this is a clang bug.  The relevant file is `lib/CodeGen/CGObjCGNU.cpp` and I (as I recall) the function it calls to generate the type encoding for the ivar has a flag to indicate whether it should provide the extended form.

**Comment by dlobron** [comment]
Thanks, David- I will check this.  We were previously using gcc with the gcc/gnustep-base runtime, and we're attempting to update to clang and libobjc2, so we've got two variables in one equation. :)  I will try compiling with gcc, and see if that gives the type info.

**Comment by dlobron** [comment]
Hey David, I rebuilt my tree with gcc, and confirmed that the problem goes away there.  So it seems like clang is not providing this info.

I looked at `lib/CodeGen/CGObjCGNU.cpp`, but I could not immediately tell what the proper option would be to tell clang to emit the class info.  Would you like me to raise this on the clang email list?  I'm kind of surprised by this bug, because my library's introspection code runs correctly on my Mac, where I'm compiling with clang.  Apple's version may have diverged from the public one in this case.

**Comment by davidchisnall** [comment]
Please can you open a clang bug and assign it to me (I'm responsible for the relevant bit of code), ideally with a test case.  The runtime-specific code paths are different on Mac and not-Mac, so you won't see this bug with OS X or iOS.

**Comment by dlobron** [comment]
Will do!

**Comment by dlobron** [comment]
I'm still waiting to be granted an llvm Bugzilla account.  As soon as I have it, I will open a clang bug as requested.  Meanwhile, I've attached a copy of a test program that reproduces the bug - rename it from .txt to .m to compile: [TestClassMetadata.txt](https://github.com/gnustep/libobjc2/files/475204/TestClassMetadata.txt)

Here is how it behaves for me on Ubuntu Linux when compiled with gcc-4.8.4:

(ALSI8)dlobron@bos-lps80:~$ ./TestClassMetadata 
2016-09-15 17:02:17.391 TestClassMetadata[13175:13175] Ivar type _intIvar does not appear to be an object-valued class: type is i
2016-09-15 17:02:17.394 TestClassMetadata[13175:13175] Ivar type _doubleVar does not appear to be an object-valued class: type is d
Calling [GSPlaceholderString -initWithBytes:length:encoding:] with incorrect signature.  Method has @36@0:8r^v16Q24i32, selector has @36@0:8^rv16Q24I32
2016-09-15 17:02:17.394 TestClassMetadata[13175:13175] Introspected class NSString for ivar name _stringIvar

I'm not sure why I get the error from GSPlaceholderString.  However, it correctly introspects the NSString ivar's class. When compiled with clang, the introspection fails:

(ALSI8)dlobron@bos-lps80:~$ ./TestClassMetadata 
2016-09-15 17:03:32.508 TestClassMetadata[13182:13182] Ivar type _intIvar does not appear to be an object-valued class: type is i
2016-09-15 17:03:32.511 TestClassMetadata[13182:13182] Ivar type _doubleVar does not appear to be an object-valued class: type is d
2016-09-15 17:03:32.511 TestClassMetadata[13182:13182] Ivar type _stringIvar does not appear to be an object-valued class: type is @

**Comment by dlobron** [comment]
I've opened a clang bug report: https://llvm.org/bugs/show_bug.cgi?id=30413

If this does turn out to be a clang issue, this issue can be closed.

**Comment by davidchisnall** [comment]
Thanks, I'll take a look at fixing it over the weekend.
