### ISSUE TITLE
My code doesn’t compile on ubuntu 

### ISSUE THREAD

**Issue by darkoverlordofdata** [gnustep/libobjc2#195]
On FreeBSD, I install gnustep, and I get the old objc runtime. Then to upgrade, I install libobjc2 and I can compile my code against the objc2 runtime and it all works. 

I’m trying to get to the same place on linux - Ubuntu 18.04, so installed gnustep. But there is no libobjc2 package, so I build this library from the latest release, and installed it. But now my code does not compile, it gets an error:  

``` 
error: expected initializer before ‘objc_method_cache_version’ 
OBJC_PUBLIC extern _Atomic(uint64_t) objc_method_cache_version; 
``` 
So, do I just have the wrong expectations for Linux? How do I get the objc2 runtime working on Ubuntu 18.04?

**Comment by davidchisnall** [comment]
It looks as if you're trying to use a compiler that doesn't support C11.  All versions of clang that support a vaguely modern Objective-C ABI should work, what are you using?

**Comment by darkoverlordofdata** [comment]
I'm using clang-7:
```
$ clang --version
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
also, I used 
```
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
```
to configure cmake

**Comment by darkoverlordofdata** [comment]
I finally figured it out. It was the GNUmakefile for my example, I added
```
CXX = clang++
CC = $(CXX)
```
and it works. I wasn't expecting the default to be gcc for the objc compiler.
