### ISSUE TITLE
1.8 doesn't seem to have the CMake fix

### ISSUE THREAD

**Issue by vincentwoo** [gnustep/libobjc2#2]
You added this patch on your fork: https://github.com/davidchisnall/libobjc2/commit/71c1437ac27d6df7f57b31974efb6fe46ac8a16e that I thought would be in 1.8, but it doesn't appear to be there. Was this intentional? It's preventing me from building on newer Clang.

**Comment by davidchisnall** [comment]
Ooops.  I forgot to merge those changes.  I'll push out a 1.8.1 this weekend with the fixes.

Sorry!

**Comment by vincentwoo** [comment]
Thanks, really appreciate it.

**Comment by davidchisnall** [comment]
I've pushed the changes into master and the 1.8.1 branch.  Can you test and let me know if anything else is broken?  I'll aim to tag the 1.8.1 version as the current 1.8.1 branch if it's all sensible.

**Comment by vincentwoo** [comment]
seems to do the trick!

**Comment by davidchisnall** [comment]
Thanks.  I've now pushed out the release and updated the FreeBSD port.  Package should be built in the next couple of days.
