### ISSUE TITLE
Deadlock in objc_send_initialize()

### ISSUE THREAD

**Issue by ngrewe** [gnustep/libobjc2#20]
Hi David,

We've discovered a fun little deadlock issue related to class initialisation. Assume two threads (1,2) and two classes (A,B) where A and B are unrelated, and A's +initialize sends a message to B:

1. Thread 1 runs and starts invoking objc_send_initialize([A class])
2. Thread 2 runs and starts invoking objc_send_initialize([A class])
3. Thread 1 is preempted by a high-priority thread when it reaches [dtable.c:855](https://github.com/gnustep/libobjc2/blob/9a2f43ca7d579928279b5d854a19adfbe43d06d6/dtable.c#L855) (right before the objc_class_flag_initialized flag is set). At this stage, it holds both the class and the runtime lock
4. Thread 2 continues running, past the block [dtable.c:830–839](https://github.com/gnustep/libobjc2/blob/9a2f43ca7d579928279b5d854a19adfbe43d06d6/dtable.c#L830-L839) (which tests the objc_class_flag_initialized flag for an early return), waiting for the runtime lock at [dtable.c:846](https://github.com/gnustep/libobjc2/blob/9a2f43ca7d579928279b5d854a19adfbe43d06d6/dtable.c#L846)
5. Thread 1 is rescheduled and relinquishes the runtime lock at [dtable.c:871](https://github.com/gnustep/libobjc2/blob/9a2f43ca7d579928279b5d854a19adfbe43d06d6/dtable.c#L871) it still holds the class lock
6. Thread 2 acquires the runtime lock, and blocks on the class lock at [dtable.c:847](https://github.com/gnustep/libobjc2/blob/9a2f43ca7d579928279b5d854a19adfbe43d06d6/dtable.c#L847)
7. Thread 1 continues running to invoke A's +initialize method and subsequently objc_send_initialize([B class]) and starts waiting on the runtime lock at [dtable.c:846](https://github.com/gnustep/libobjc2/blob/9a2f43ca7d579928279b5d854a19adfbe43d06d6/dtable.c#L846)

Now you have a deadlock: Thread 1 is waiting for thread 2 to release the runtime lock and thread 2 is waiting for thread 1 to release the class lock.

I think it might be a solution to acquire the runtime lock before the objc_class_flag_initialized test on line 830 (and unlocking it right after taking the branch, before acquiring the class lock).

**Comment by davidchisnall** [comment]
This sounds like the same deadlock that exists in Apple's runtime, where two mutually dependent classes receive +initialize messages at the same time.  Can it occur in programs where this isn't the case?

**Comment by ngrewe** [comment]
> This sounds like the same deadlock that exists in Apple's runtime, where two mutually dependent classes receive +initialize messages at the same time. 

Yeah, I'd say that would be just be a bug in the calling code. But this is a different situation.

> Can it occur in programs where this isn't the case?

Yes. The example above doesn't have any cyclic dependencies between the +initialize methods. It's just one class (A) being sent +initialize concurrently on two threads, triggering initialisation of a second class along the way (it doesn't matter which one). So you don't have a  deadlock between two different class locks, but a highly timing-dependent one between the runtime lock and the class-specific lock instead.

**Comment by davidchisnall** [comment]
I see (first cup of coffee of the day, brain slowly starting to work...).  This looks like a classic lock-order reversal (if only the WITNESS port to userspace had been finished...).  I think that the correct solution is probably to drop the class lock when you drop the runtime lock and then reacquire them in the correct order (class lock then runtime lock).

All of this code can probably be modified to add a couple more blocks and use `LOCK_[RUNTIME]_FOR_SCOPE` too.

**Comment by ngrewe** [comment]
> I think that the correct solution is probably to drop the class lock when you drop the runtime lock and then reacquire them in the correct order (class lock then runtime lock).

That sounds like the textbook solution. The problem I see with this is that acquiring the class lock on l. 835 then no longer guarantees that the function only returns after +initialize has finished executing.

Do you have a comment on my suggestion from above?

> I think it might be a solution to acquire the runtime lock before the objc_class_flag_initialized test on line 830 (and unlocking it right after taking the branch, before acquiring the class lock).

This would ensure that once the first thread obtains the runtime lock, any subsequent thread will only hold a single lock at a time, thus preventing the deadlock.

**Comment by davidchisnall** [comment]
Your solutions sounds fine.

**Comment by ngrewe** [comment]
Thanks for merging the fix!
