### ISSUE TITLE
PropertyAttribute_legacy tests fails

### ISSUE THREAD

**Issue by rmottola** [gnustep/libobjc2#224]
Hi,

both on Linux/i686 (clang 13) and FreeBSD/amd64 (clang 10) I get two test failures:

```
         71 - PropertyAttributeTest_legacy (Subprocess aborted)
         72 - PropertyAttributeTest_legacy_optimised (Subprocess aborted)
```

**Comment by davidchisnall** [comment]
Please can you show the output of running this test?

**Comment by rmottola** [comment]
I just tried on Linux/i686 and I get other failures now, no longer this one. I'll open a separate one.
I did not remember which FreeBSD system I tested. On my laptop with FreeBSD all tests pass. I will test on my other two FreeBSD systems next week. They are all amd64, I have no 32bit FreeBSD system. If all pass, I'll close this one.
