### ISSUE TITLE
Build error with Visual Studio 17.1 due to stdatomic.h

### ISSUE THREAD

**Issue by triplef** [gnustep/libobjc2#225]
The [latest CI build](https://github.com/gnustep/tools-windows-msvc/runs/5370409602?check_suite_focus=true) of the GNUstep MSVC toolchain failed building the libobjc2 tests with this [error](https://github.com/gnustep/tools-windows-msvc/runs/5370409602?check_suite_focus=true#step:7:706):

> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\stdatomic.h(15,2): error: <stdatomic.h> is not yet supported when compiling as C, but this is planned for a future release.

What changed since the [last CI build](https://github.com/gnustep/tools-windows-msvc/runs/5016646442?check_suite_focus=true) is that the GitHub Runner VM was updated from [20220116.1](https://github.com/actions/virtual-environments/blob/win22/20220116.1/images/win/Windows2022-Readme.md) to [20220220.1](https://github.com/actions/virtual-environments/blob/win22/20220220.1/images/win/Windows2022-Readme.md), which includes a Visual Studio update from 17.0 to 17.1. The [changelog](https://github.com/microsoft/STL/wiki/Changelog) contains the following change regarding stdatomic:

> [P0943R6](https://wg21.link/P0943R6) [#2008](https://github.com/microsoft/STL/pull/2008) Supporting C Atomics In C++
> * Note: <stdatomic.h> is currently supported when compiling as C++ (/std:c++latest). It is not yet supported when compiling as C (/std:c11 and /std:c17), but support for C atomics is planned for a future release. For more info, see the September 2020 blog post ["C11 and C17 Standard Support Arriving in MSVC"](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/).

Not sure if I’m missing something, though it seems a bit crazy that they would have broken stdatomic support in C with this release. Any ideas how to work around this?

**Comment by davidchisnall** [comment]
We're compiling with clang, and I believe clang has a `stdatomic.h` that does `#include_next` of the system one if it exists.  I think in MSVC `_Atomic(T)` is defined as `std::atomic<T>`, so we could compile those files in C++ mode.

We only use `stdatomic.h` in tests, so we could probably just skip them on Windows.

**Comment by triplef** [comment]
Thanks for your input David. I found that this has been worked around in Clang: https://github.com/llvm/llvm-project/commit/1ad7de9e92bc2977698e5f6d6493202b50c912d5

I’ll simply disable building the tests for now until this patch or C atomics land with a future VS update.
