### ISSUE TITLE
Crash under clang14 in release mode on windows

### ISSUE THREAD

**Issue by levinli303** [gnustep/libobjc2#230]
<img width="477" alt="Screen Shot 2022-08-22 at 09 44 45" src="https://user-images.githubusercontent.com/17924287/185822957-c6346faa-1a4f-4a02-9901-d017c7cfd6eb.png">

After updating Visual Studio to 17.3 (which updated clang to clang 14), I'm noticing a crash in some methods when built with clang 14 in release mode on Windows. This only happens with clang 14 + Release. Does not happen with clang 13, or in debug mode. Using example project in https://github.com/gnustep/tools-windows-msvc

One example is to use this method
```[NSProgress progressWithTotalUnitCount:10];```

This crash does not happen if I write
```[[NSProgress alloc] initWithParent:nil userInfo:nil];```

**Comment by triplef** [comment]
This is probably related to this bug:
https://github.com/llvm/llvm-project/issues/56952

For the time being I’d recommend sticking with Clang 13. You can use one of the official downloads from the LLVM website instead of using the Visual Studio one.

**Comment by levinli303** [comment]
looks like it.
it is possible to use a custom LLVM toolchain in Visual Studio [too](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#custom_llvm_toolset). might be good to mention it in the msvc-tools repo about this bug.

**Comment by weliveindetail** [comment]
@levinli303 Can you run the test suite for libobjc2 and check if you see these failing:
```
7 - ARCTest_arc (Exit code 0xc0000409)
8 - ARCTest_arc_optimised (Exit code 0xc0000409)
41 - PropertyIntrospectionTest2_arc (SEGFAULT)
42 - PropertyIntrospectionTest2_arc_optimised (SEGFAULT)
```
I am looking into these failures right now. Might be good to know if this is one and the same issue.

**Comment by levinli303** [comment]
@weliveindetail  do you still need me to run these tests? I'm not sure how to do so, if you can provide some commands to allow me to run the tests I can do it in the coming few days.

**Comment by triplef** [comment]
> might be good to mention it in the msvc-tools repo about this bug.

I’ve added a section about known compiler issues in the readme:
https://github.com/gnustep/tools-windows-msvc#status-and-known-issues

**Comment by levinli303** [comment]
@weliveindetail 
I'm seeing 
```
    lld-link: error: could not open 'kernel32.lib': no such file or directory
    lld-link: error: could not open 'user32.lib': no such file or directory
    lld-link: error: could not open 'gdi32.lib': no such file or directory
    lld-link: error: could not open 'winspool.lib': no such file or directory
    lld-link: error: could not open 'shell32.lib': no such file or directory
    lld-link: error: could not open 'ole32.lib': no such file or directory
    lld-link: error: could not open 'oleaut32.lib': no such file or directory
    lld-link: error: could not open 'uuid.lib': no such file or directory
    lld-link: error: could not open 'comdlg32.lib': no such file or directory
    lld-link: error: could not open 'advapi32.lib': no such file or directory
    lld-link: error: could not open 'msvcrtd.lib': no such file or directory
    lld-link: error: could not open 'oldnames.lib': no such file or directory
    ninja: build stopped: subcommand failed.
```

with the `cmake -GNinja ...` command

**Comment by weliveindetail** [comment]
@levinli303 Did you run this from your Visual Studio command line?

**Comment by levinli303** [comment]
@weliveindetail  the test suite are all passing for this clang version (I need to set CMAKE_C_COMPILER to clang instead of clang-cl, otherwise it will complain import is not a MSVC feature)
```
clang version 14.0.5
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin
```

**Comment by davidchisnall** [comment]
Is this now fixed?

**Comment by levinli303** [comment]
based on https://github.com/gnustep/tools-windows-msvc#status-and-known-issues, it is fixed in clang 16.

**Comment by triplef** [comment]
Yes this was fixed in Clang 16. You can get the RC build here if you want to give it a try to confirm:
https://github.com/llvm/llvm-project/releases

In the discussions around this fix there were some open questions around whether the GNUstep runtime needs/uses markers for ObjC ARC autorelease optimization. @davidchisnall could you still chime in on that?

From https://github.com/llvm/llvm-project/issues/56952#issuecomment-1256136782:

> @davidchisnall Is GNUstep checking for optimized callers like the callerAcceptsOptimizedReturn() in Apple's ObjC runtime here? https://opensource.apple.com/source/objc4/objc4-818.2/runtime/objc-object.h.auto.html

From https://reviews.llvm.org/D134441#3810388:

> It's possible the GNU runtime generally uses a different approach and doesn't need these markers at all; David Chisnall might know.
