### ISSUE TITLE
AssociatedObject and BlockImpTest failures on Linux

### ISSUE THREAD

**Issue by rmottola** [gnustep/libobjc2#232]
I just tested on Linux/x86 with clang 14.0.6
```
         19 - AssociatedObject_legacy (Subprocess aborted)
         20 - AssociatedObject_legacy_optimised (Subprocess aborted)
         26 - BlockImpTest_optimised (SEGFAULT)
         28 - BlockImpTest_legacy_optimised (SEGFAULT)
```

**Comment by rmottola** [comment]
AssociatedObject_legacy: malloc.c:2617: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
<end of output>

AssociatedObject_legacy_optimised: malloc.c:2617: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
<end of output>

**Comment by davidchisnall** [comment]
This looks like heap corruption.  Can you run the test with valgrind?

**Comment by davidchisnall** [comment]
Not enough information to debug or reproduce.  Please reopen this if you are able to run the tests with valgrind or asan.
