### ISSUE TITLE
Error while building on Windows using MSVC...

### ISSUE THREAD

**Issue by gcasa** [gnustep/libobjc2#243]
Hey David, I am seeing the following error:

```
C:/src/tools-windows-msvc-master-branch/src/libobjc2/associate.m(171,2): error: cannot use '@try' with Objective-C exceptions disabled
        @try
        ^
1 warning and 1 error generated.
```

**Comment by triplef** [comment]
I’m guessing you’re missing the `-fobjc-exceptions` compiler flag.

You can find the flags needed e.g. here in the readme:
https://github.com/gnustep/tools-windows-msvc#using-the-toolchain-from-the-command-line
