### ISSUE TITLE
[Question] How is it compared with other solutions?

### ISSUE THREAD

**Issue by iahunq** [gnustep/libobjc2#245]
The project doesn't open Github Discussions so I posted here (which I think is a wrong place to ask questions like this). How is GNUStep compared with ObjFW (https://github.com/ObjFW/ObjFW) and mulle-objc (https://mulle-objc.github.io/)?

**Comment by davidchisnall** [comment]
GNUstep implements the OpenStep and Cocoa APIs. It aims for source compatibility with NeXT and OS X implementations. The other two projects define their own APIs.

The runtime, specifically, aims for feature parity (and the occasional unique feature) with Apple’s implementation. It is used by WinObjC and GNUstep to provide the Objective-C implementation.
