### ISSUE TITLE
alignTest and alignTest_optimised fails on FreeBSD 11-RELEASE

### ISSUE THREAD

**Issue by cyclaero** [gnustep/libobjc2#26]
The system is: `FreeBSD 11.0-RELEASE-p3 amd64`
The CPU is: `Intel(R) Atom(TM) CPU D510  @ 1.66GHz (1666.72-MHz K8-class CPU)`
The clang version is: `FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)`

On the console I executed as root:

    # svn checkout https://github.com/gnustep/libobjc2/trunk/ libobjc2
    # cd libobjc2; mkdir build; cd build
    # cmake ..
    # make
    # make test

    Test project /root/install/libobjc2/build
          Start  1: alignTest
     1/52 Test  #1: alignTest ..................................***Exception: Other  0.43 sec
          Start  2: alignTest_optimised
     2/52 Test  #2: alignTest_optimised ........................***Exception: Other  0.38 sec
    ...

    # Test/alignTest
    --> self: 0x801829128 Addr: 0x801829140
    --> Assertion failed: (o_isa == 0), function main, file /root/install/libobjc2/Test/alignTest.m, line 83.
    --> Abort (core dumped)

All the other tests succeeded.

**Comment by davidchisnall** [comment]
Yup, they were added to remind me about a known bug.  6b285936bed090d06f3bfc66d0886c12dc088753 is currently more reliable than head.

**Comment by cyclaero** [comment]
I was sure that my `svn checkout` from GitHub included all the latest changes, however, I juzt verified it again, and it does include [6b28593](https://github.com/gnustep/libobjc2/commit/6b285936bed090d06f3bfc66d0886c12dc088753) . So, at least on FreeBSD with clang 3.8, this still cored dumps.

**Comment by davidchisnall** [comment]
Yes, use that commit, not head.

**Comment by cyclaero** [comment]
OK, now I understand.

**Comment by davidchisnall** [comment]
Should be fixed in 5725aa7

**Comment by cyclaero** [comment]
Perfect, I tested this also with my code, and everything is working well.
Thank you very much.
