### ISSUE TITLE
make test fails on FreeBSD 10 (but not on 11)

### ISSUE THREAD

**Issue by minusbat** [gnustep/libobjc2#28]

**Comment by minusbat** [comment]
I guess maybe this is a result of yesterdays patch ? This works on 11, and the actual library seems to work with code, but it makes me uncomfortable given which test is failing!

The following tests FAILED:
	 45 - objc_msgSend (SEGFAULT)
	 46 - objc_msgSend_optimised (SEGFAULT)
Errors while running CTest
*** Error code 8

**Comment by minusbat** [comment]
Just checked, this is a clang version issue as clang38 works fine on FreeBAD 10. The default in 10 is 3.1, the default in 11 is 3.8, hence the difference I guess.

**Comment by cyclaero** [comment]
I see the same, when compiling on FreeBSD 11 with `CMAKE_BUILD_TYPE = Release`. When leaving `CMAKE_BUILD_TYPE` empty, all tests are passed.

**Comment by minusbat** [comment]
This issue is wrong. I see failures on both 10 and 11. Will close and reopen with proper debugging info.
