### ISSUE TITLE
Cut a 2.2.1 release?

### ISSUE THREAD

**Issue by qmfrederik** [gnustep/libobjc2#281]
There was a suggestion of cutting a 2.2.1 release here: https://github.com/gnustep/libobjc2/pull/274#issuecomment-1927509927 

On top of that, a lot of fixes MSYS2-related fixes were merged after the 2.2 release, together with PowerPC-related work: https://github.com/gnustep/libobjc2/pull/272

@davidchisnall Given all that, do you think it makes sense to cut a 2.2.1 release?

**Comment by hmelder** [comment]
Can we create a new ANNOUNCE file in this release?

**Comment by davidchisnall** [comment]
Yes.  I think the best thing is to create a 2.2.1 branch from 2.2, cherry pick all of the fixes in, and create a new ANNOUNCE there.

**Comment by qmfrederik** [comment]
I can't think of anything which is in trunk which shouldn't be in 2.2.1, so I believe you could just branch master.

**Comment by davidchisnall** [comment]
The main thing is that the announce for trunk is now for 2.3.
