### ISSUE TITLE
-DCMAKE_BUILD_TYPE=Release fails tests on FreeBSD

### ISSUE THREAD

**Issue by minusbat** [gnustep/libobjc2#29]
This happens on both 10 and 11, no matter what compiler is used.

The following tests FAILED:
	 45 - objc_msgSend (SEGFAULT)
	 46 - objc_msgSend_optimised (SEGFAULT)

Running gdb 7.12 against these gives the following trace:

(gdb) bt
#0  0x000000080083e1d0 in objc_msgSend_fpret ()
   from /home/pete/libobjc2-test/libobjc.so.4.6
#1  0x00000000004011f8 in main ()
    at /home/pete/libobjc2-test/Test/objc_msgSend.m:199

I tried to get gdb to give me more info by adding -gdwarf-4 -fno-omit-frame-pointer -fno-strict-aliasing -fstack-protector to the build but it gives me the same result.

the failing test is in the registration of small object classes here:

        assert(objc_registerSmallObjectClass_np(objc_getClass("Test"), 1));
        a = objc_msgSend((id)01, @selector(foo));

The assert passes - i.e. the small class is added with location '1' - but the subsequent message send fails. This is in objc_msgSend.x86-64.S: and I don't do amd64 assembler in any depth unfortunately (too old, give me Vax 11 or 68k and I'm fine :-) ) so I can't debug this any further. If the issue is in the assembly language code though then it is a bit odd, as surely the optimiser (which is what is enabled in Release) would not affect that ?

**Comment by davidchisnall** [comment]
This is a build system bug.  For some reason, we're building the tests with `-DNDEBUG`, in release mode.  This means that the `assert()` is compiled out in the test and we never register the small object class.

**Comment by minusbat** [comment]
Ah, OK, I understand that. Could you jsut rewiet the test to take the regestrayion out of the assert for now so that the tests pass ? I would like to run it compiled 'Release' if possible. Can do this and submit a pull reqauest if you like (have never learned how to do those on github, seems like as good a place as any to start!)

**Comment by davidchisnall** [comment]
Running the tests without assertions doesn't really make sense - they'll all pass.  With the change, the tests are compiled with `-UNDEBUG`, so asserts still fire, but the rest of the library is compiled in whatever mode you select.
