### ISSUE TITLE
Crashes in fast_paths.m when class argument is null

### ISSUE THREAD

**Issue by rfm** [gnustep/libobjc2#302]
The subject says it ... the functions in fast_paths.m don't check for a null argument and hence crash when dereferencing the null pointer.
It's easy to demonstrate with a pattern like:

Class
getClassNamed(char *name)
{
  return Nil;
}

id obj = [[getClassNamed("dummy") alloc] init];

**Comment by rfm** [comment]
In case it's relevant to compiler behavior changes; I found this using clang 18.1.3 on apple silicon.
I have zero experience with github PRs ... so it's probably quicker for you just to add 'if (Nil == cls) return nil;' to two functions.

**Comment by davidchisnall** [comment]
I probably won't get to it for a week or so.  Raising a PR isn't exactly hard: clone the repo, commit the fix, push it to a branch in this repo, open the link that git tells you for raising the PR.
