### ISSUE TITLE
method_setImplementation/exchangeImplementations does not work on resolved metaclasses

### ISSUE THREAD

**Issue by DHowett-MSFT** [gnustep/libobjc2#32]
When you use `method_setImplementation(Method, IMP)` or `method_exchangeImplementations(Method, Method)` on a method retrieved from a metaclass and that metaclass is fully resolved, its dtable will not be updated to point to the new IMP.

Example code:

```objc
__attribute__((objc_root_class))
@interface Issue32Test
+ (void)noop; // call to force resolution
+ (int)test1;
+ (int)test2;
@end

@implementation Issue32Test
+ (void)noop { }
+ (int)test1 { return 1024; }
+ (int)test2 { return 2048; }
@end

int main(int argc, char** argv) {
    [Issue32Test noop]; // <-- A
    Class i32meta = object_getClass(objc_getClass("Issue32Test"));
    Method m1 = class_getInstanceMethod(i32meta, @selector(test1));
    Method m2 = class_getInstanceMethod(i32meta, @selector(test2));
    method_exchangeImplementations(m1, m2);
    assert(2048 == [Issue32Test test1]);
}
```

If you remove message send A, the assert passes.

This appears to be due to a bug in the design of `objc_updateDtableForClassContainingMethod`. It iterates over every class (not metaclass!) known to the runtime and updates the dtable of the first class containing that method.

_Moved from Microsoft/WinObjC#1639._

**Comment by davidchisnall** [comment]
Thanks for the report.
