### ISSUE TITLE
libobjc2 does not provide Block.h and Block_private.h

### ISSUE THREAD

**Issue by theiostream** [gnustep/libobjc2#34]
libobjc2's block headers are at `objc/blocks_runtime.h` and `objc/blocks_private.h` respectively, and I understand there must have been a good reason to keep them with these names instead of the ones in Apple's API. However, this breaks compatibility with a lot of applications that try to access block runtime declarations in this "standard" location, and building them requires manually setting up symlinks to these files.

Would it make sense to create `Block.h` and `Block_private.h` as symlinks to the GNUstep block headers in the install routine? The issue I can think of is generating conflicts with systems that ship with these headers (like OSX) or with other libraries that implement the block runtime (e.g. libBlocksRuntime on Linux), but it seems like these cases could be easily handled on the install routine.

**Comment by davidchisnall** [comment]
There are two reasons for this:

1. libobjc2 shipped with blocks before Apple, so there wasn't an Apple API to copy at that point.
2. Deployment platforms (e.g. FreeBSD) ship these headers as part of the system (they come from LLVM's libBlocksRuntime) and so there's the potential for them to conflict.

I don't think that either of these are actually a blocker: FreeBSD puts the system ones in `/usr/include`.

**Comment by theiostream** [comment]
Will close, since pull request #36 covers this.
