### ISSUE TITLE
object_setInstanceVariable() -- Segfault

### ISSUE THREAD

**Issue by xFAR** [gnustep/libobjc2#39]
The current (1.8.1 and Git master) implementations of object_setInstanceVariable() trigger a Segault if the caller tries to set a non-existent ivar.  This can happen when a NIB is loaded.  A graceful exit with a NULL return value would seem to be better behavior. 

With 1.8.x I fix this issue with the following:

```
void object_setIvar(id object, Ivar ivar, id value)
{
	char *addr = (char*)object;
+	unsigned offset;
	
+	if (ivar && (offset = ivar_getOffset(ivar)))
+	    {
-	addr += ivar_getOffset(ivar);
+	    addr += offset;
	    *(id*)addr = value;
+	    }
}
```

The Git master code also blows up when determining the encoding type of a non-existent ivar:

```
Ivar object_setInstanceVariable(id obj, const char *name, void *value)
{
	Ivar ivar = class_getInstanceVariable(object_getClass(obj), name);
-->	if (ivar_getTypeEncoding(ivar)[0] == '@')

```

**Comment by davidchisnall** [comment]
Please can you submit a pull request with this patch?

**Comment by davidchisnall** [comment]
This was fixed by merging the pull request.
