### ISSUE TITLE
Updated guide to install on Ubuntu

### ISSUE THREAD

**Issue by horaciojcfilho** [gnustep/libobjc2#42]
Hello,

It is not a issue, sorry in advance, however could you point me an updated article to install libobjc2 on Ubuntu 17.04? I would like to use blocks and ARC support as well.

Thanks in advance :+1:

**Comment by davidchisnall** [comment]
I'm not sure of one, but you should simply be able to run cmake.  The install defaults to `/usr/local`, so you probably want to use `ccmake` to tweak that to `/usr` on Ubuntu.

**Comment by ceztko** [comment]
Is there any reason why libobjc2 is not packaged inside [gnustep-devel](https://packages.ubuntu.com/search?keywords=gnustep-devel) in ubuntu/debian?
