### ISSUE TITLE
MinGW support?

### ISSUE THREAD

**Issue by tumagonx** [gnustep/libobjc2#44]
I tried to build master branch with gcc 4.8.5 and gcc 5.2.0 (with help from mman-win32 project) but stuck at assembly source :
```
c:/msys32/gcc48/bin/../lib/gcc/i686-w64-mingw32/4.8.5/../../../../i686-w64-mingw32/bin/as.exe: BFD (tumaG86) 2.28.1 assertion fail ../../binutils-2.28.1/bfd/coff-i386.c:574
E:/Sources/libobjc2-master/objc_msgSend.x86-32.S: Assembler messages:
E:/Sources/libobjc2-master/objc_msgSend.x86-32.S:78: Error: cannot represent relocation type BFD_RELOC_386_GOTPC
c:/msys32/gcc48/bin/../lib/gcc/i686-w64-mingw32/4.8.5/../../../../i686-w64-mingw32/bin/as.exe: BFD (tumaG86) 2.28.1 assertion fail ../../binutils-2.28.1/bfd/coff-i386.c:574
E:/Sources/libobjc2-master/objc_msgSend.x86-32.S:82: Error: cannot represent relocation type BFD_RELOC_386_GOTPC
c:/msys32/gcc48/bin/../lib/gcc/i686-w64-mingw32/4.8.5/../../../../i686-w64-mingw32/bin/as.exe: BFD (tumaG86) 2.28.1 assertion fail ../../binutils-2.28.1/bfd/coff-i386.c:574
E:/Sources/libobjc2-master/objc_msgSend.x86-32.S:86: Error: cannot represent relocation type BFD_RELOC_386_GOTPC
make[2]: *** [CMakeFiles/objc.dir/build.make:577: CMakeFiles/objc.dir/objc_msgSend.S.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:61: CMakeFiles/objc.dir/all] Error 2
make: *** [Makefile:144: all] Error 2
```

**Comment by tumagonx** [comment]
Honestly I don't know which bug is this? gcc, binutils or libobjc...

**Comment by davidchisnall** [comment]
What happens if you try to build with clang?  gcc's support for Objective-C is pretty useless and I believe it has been built with on Windows with clang before.  That said, if you're targeting Windows, I'd recommend looking at Microsoft's fork in the WinObjC project, which has a few patches that haven't yet been merged upstream for better interop with Windows C++ exceptions.

**Comment by tumagonx** [comment]
I need XP support , winobjc has demanding development tools and might not support XP as it under MS.
With gnustep-base and gcc libobjc things already works for me. I just want to see if libobjc2 improve things as it claim.

**Comment by tumagonx** [comment]
I need XP support , winobjc has demanding development tools and might not support XP as it under MS.
With gnustep-base and gcc libobjc things already works for me. I just want to see if libobjc2 improve things as it claim. 
With clang it just handover it back to gas. hence same error

**Comment by davidchisnall** [comment]
Try clang -integrated-as.

**Comment by davidchisnall** [comment]
(Note: This may still not work and we might need different relocation types on Windows)

**Comment by davidchisnall** [comment]
Closing due to lack of feedback from submitter, please reopen if still relevant.
