### ISSUE TITLE
Failing test in PropertyIntrospectionTest2

### ISSUE THREAD

**Issue by ngrewe** [gnustep/libobjc2#5]
I upgraded to clang 3.7 (from 3.4, I think) last night, and I'm now getting a test failure in [PropertyIntrospectionTest2](https://github.com/gnustep/libobjc2/blob/27933a9be7018567573a7d8b7ce749ddac331029/Test/PropertyIntrospectionTest2.m#L520-L523). The test expects `T@,R,N,VidReadonlyWeakNonatomic`, but what I get from the compiler (checked the binary) is now `T@,R,W,N,VidReadonlyWeakNonatomic`. Since `W` is the attribute char for weak properties, it seems to me that the test now expects the wrong thing (probably the weak attribute wasn't supported in earlier version of clang?). 

We could make this conditional on the compiler version, but maybe there is a feature check macro that can be used? Or maybe we just want the test to fail on earlier versions of clang?

**Comment by davidchisnall** [comment]
I thought I'd fixed all of these.  The correct fix is probably to accept either variant.

**Comment by ngrewe** [comment]
Actually, it get's a bit more weird: The weak annotation is present in the type signature but not in in the attributes2 member of the property structure. This is due to this code in [CGObjCGNU.cpp](https://github.com/llvm-mirror/clang/blob/141607fa7fb12029f3e47192f430511673385e71/lib/CodeGen/CGObjCGNU.cpp#L254-L259): 

```cpp
    if (attrs & ObjCPropertyDecl::OBJC_PR_readonly) {
      attrs &= ~ObjCPropertyDecl::OBJC_PR_copy;
      attrs &= ~ObjCPropertyDecl::OBJC_PR_retain;
      attrs &= ~ObjCPropertyDecl::OBJC_PR_weak;
      attrs &= ~ObjCPropertyDecl::OBJC_PR_strong;
    }
```

Since the property is read only, the weak flag gets cleared. Behaviour with the Apple runtime is to keep the weak flags.

**Comment by davidchisnall** [comment]
This looks like a clang bug then.  This code in clang is a bit horrible, because it was a quick hack to add property introspection the week before a release branched.  For Clang 3.8 / libobjc2 2.0, I'm planing on introducing a new ABI that fix a number of these issues.  For now, the best thing to do is make the libobjc2 tests permissive to expected clang values.
