### ISSUE TITLE
CMake does not recognize OLDABI_COMPAT

### ISSUE THREAD

**Issue by ePirat** [gnustep/libobjc2#74]
Trying to run CMake with `-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DCMAKE_ASM_COMPILER=clang -DCMAKE_ASM_FLAGS=-c -DTESTS=OFF -DOLDABI_COMPAT=OFF` I get a CMake warning:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    OLDABI_COMPAT
```

**Comment by ePirat** [comment]
Apparently this is only available in current master, not the last release. Sorry.

**Comment by davidchisnall** [comment]
The last release is quite old at this point.  There are currently two branches edging towards a release.  The 1.9 release branch will be released as 1.9 soon and is the last release using the old ABI internally.  The current master branch will be released as 2.0 at some point after that and uses the new ABI internally, upgrading old data structures to look like the new ones.  If you want to test the master branch with the new ABI, you will need to manually apply the clang patch, or wait for it to be merged (probably tomorrow).

**Comment by ePirat** [comment]
Thanks for clarifying.

Another thing I was wondering is if providing NSObject (or equivalent base class) is out of scope of libobcj2? (Sorry that I am asking this here, I could not find any other place to ask questions. Let me know if there is one.)

**Comment by davidchisnall** [comment]
It's out of scope.  The runtime aims to provide everything needed to implement NSObject, but NSObject belongs in the Foundation framework.  You can find implementations of NSObject designed to work with this runtime in [GNUstep Base](https://github.com/gnustep/libs-base) and the [Windows bridge for iOS](https://github.com/Microsoft/WinObjC).
