### ISSUE TITLE
-fconstant-string-class error...

### ISSUE THREAD

**Issue by GalenRhodes** [gnustep/libobjc2#77]
Some time after 2018-03-28 GNUstep Base started failing during "configure" with the error message:

> Your compiler does not appear to implement the -fconstant-string-class option needed for support of strings.

**Comment by GalenRhodes** [comment]
If I use the "1.9" branch it's fine. Problem only occurs in the main branch.

**Comment by andreasfink** [comment]
run into the same problem.     git clone https://github.com/gnustep/libobjc2 --branch 1.9
is really what made it work. Debian9 with clang7 here.

**Comment by davidchisnall** [comment]
There was a clang bug that prevented this from working with -fobjc-runtime=gnustep-2.0.  This is now fixed in svn head and there's a back-port of the fix to 7.0 under review for the FreeBSD package.
