### ISSUE TITLE
Block.h and Block_private.h symlinks don't work.

### ISSUE THREAD

**Issue by ngrewe** [gnustep/libobjc2#79]
PR #36 added symlinks to the libBlocksRuntime specific header locations (Block.h and Block_private.h in the top level header directory of the install prefix).
I've just tried to upgrade the libdispatch version used in the travis CI script for gnustep-base to the Swift corelibs (read: not horribly outdated) one and wanted to take advantage of that. As it turns out, the symlinks don't work so well:

https://travis-ci.org/ngrewe/base/jobs/476074822

As you can see, they can't find Availability.h  (which would be expected, since it's located in the objc subdirectory).

A possible fix would be to install compatibility headers (just `#inlcude`ing the libobjc2 headers) instead of dumb symlinks.

**Comment by davidchisnall** [comment]
Probably the simplest fix is to change the `"Availability"` to `<objc/Availability>`.  That might break the headers in the not-installed configuration, but shouldn't be a problem.  Can you test it, and if it works push it to master and the 1.9 branch?

**Comment by davidchisnall** [comment]
Ooops, didn't see the pull request.  That's a cleaner fix!
