### ISSUE TITLE
New release and Building instruction?

### ISSUE THREAD

**Issue by alexmyczko** [gnustep/libobjc2#81]
Is there a plan for a new release now?

What about building order and compiler to be used?
clang 3.1+, gnustep-make, -base, gui, back, libobjc2 or libobjc2 first?
(found the clang 3.1+ ref at https://en.wikipedia.org/wiki/Objective-C#Blocks)
However Debian (sid) has 6.0, 7, and 8

There is 
https://github.com/gnustep/libobjc2/blob/master/ANNOUNCE.1.9 but I
can't find anything under releases...

Some distributions ship 1.8:
https://repology.org/metapackage/libobjc2/versions

**Comment by davidchisnall** [comment]
I plan on doing two releases soon, one from the 1.9 branch and one (2.0) from the master branch.  1.9 will be the last release using the old ABI.  For 2.0, you want LLVM 8.0 or later (currently, ELF platforms only, hopefully Windows soon.  A recent svn nightly build is fine until 8.0 is released), the latest GNUstep, and to use the `-fobjc-runtime=gnustep-2.0` flag when compiling.  

In both cases, build and install libobjc2 first, then gnustep.  I have built the FreeBSD GNUstep ports and tested most of them with the new ABI, so I'm fairly confident that the master branch is stable enough for a release.

**Comment by alexmyczko** [comment]
can you do the release before 12th February? so i could try getting this into debian (buster)...

**Comment by davidchisnall** [comment]
I guess I missed the deadline for Debian.  The 2.0 branch is now packaged on FreeBSD and getting some testing.  It's been far too long since the last release, so I really need to push both of them out soon...

**Comment by alexmyczko** [comment]
Absolutely missed it! However, I'm still looking forward to 1.9 and 2.0 to try them personally, have a Debian package (the next stable release will be in 2-3 years) but that shall not hinder anyone to use this newer version building it all themselves.

My Plan was if all works well to use 1.9 (or 2.0 if clang versions allow), and bring out http://livecd.gnustep.org/ GNUSTEP-3

**Comment by alexmyczko** [comment]
Ping, any news?

**Comment by davidchisnall** [comment]
I am happy to package the 2.0 branch on FreeBSD, because I am testing it there.  I am not going to do any official releases until I hear back from other people testing and reporting success.

**Comment by alexmyczko** [comment]
So I will grab a daily co and try?

**Comment by davidchisnall** [comment]
Please do.  If Debian and FreeBSD both work with the 2.0 release, then I'm much more confident about doing a proper release.

**Comment by davidchisnall** [comment]
I'm not sure what dh_install is, but libobjcxx.so is gone.  For backwards compatibility, you can install a symlink to libobjc.so if you want.

The 1.9 branch will be released as 1.9, trunk will be released as 2.0.  Note that BFD ld probably doesn't link the 2.0 ABI correctly, you will need to use lld or gold (and a few things don't work with LLD).

**Comment by alexmyczko** [comment]
Will it be enough to just have lld installed? Or must it be called "ld"? I mean does your build system try to run lld if it's there, falling back to ld? 

No idea what "gold" is?

**Comment by davidchisnall** [comment]
You may need to add -fuse-ld=lld to your the linker flags.

**Comment by davidchisnall** [comment]
I have now pushed releases from the 1.9 and 2.0 branches.
