### ISSUE TITLE
Category implementing protocol causing undefined reference using 2.0 ABI

### ISSUE THREAD

**Issue by triplef** [gnustep/libobjc2#90]
Using the 2.0 ABI, a category implementing a protocol causes the following linker error:

`CategoryProtocolTest.m.o:CategoryProtocolTest.m:.objc_protocol_list: error: undefined reference to '._OBJC_PROTOCOL_TestProtocol'`

Compiling the same code using the 1.9 ABI works fine.

The issue can be reproduced with the following test code:

#### CategoryProtocolTest.h
```objc
#import <Foundation/Foundation.h>

@protocol TestProtocol <NSObject>
@end

@interface CategoryProtocolTest : NSObject
@end

@interface CategoryProtocolTest (TestCategory) <TestProtocol>
@end
```

#### CategoryProtocolTest.m
```objc
#import "CategoryProtocolTest.h"

@implementation CategoryProtocolTest
@end

@implementation CategoryProtocolTest (TestCategory)
@end
```

The test was done using libobjc2 with GNUstep on Android. Following is the full linker command line. Please let me know if any further details would be helpful.

```
/Users/me/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/me/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/me/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o /Users/me/hello-objectivec/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so CMakeFiles/native-lib.dir/native-lib.cpp.o CMakeFiles/native-lib.dir/GSInitialize.m.o CMakeFiles/native-lib.dir/ObjectiveCTest.mm.o CMakeFiles/native-lib.dir/CategoryProtocolTest.m.o  -llog -rdynamic -L/Users/me/Library/Android/sdk/ndk-bundle/sysroot/usr/lib -fexceptions -fobjc-runtime=gnustep-2.0 -fblocks -L/Users/me/Library/Android/GNUstep/lib/ -lgnustep-base -lobjc -lm -ldispatch -lBlocksRuntime -latomic -lm && cd /Users/me/hello-objectivec/app/.externalNativeBuild/cmake/debug/armeabi-v7a && /Users/me/Library/Android/sdk/cmake/3.6.4111459/bin/cmake -E copy /Users/me/Library/Android/GNUstep/lib/*.so /Users/me/hello-objectivec/app/build/intermediates/cmake/debug/obj/armeabi-v7a/
```

**Comment by davidchisnall** [comment]
Thanks.  I can reproduce this, I'll investigate.

**Comment by davidchisnall** [comment]
...but only with an older clang.  This is fixed in clang trunk and the fix is back-ported to the llvm70 FreeBSD package, which is why I haven't seen it.

**Comment by triplef** [comment]
We’re using clang from the latest Android NDK package (v19.1.5304403) with the following version info:

```
Android (5058415 based on r339409) clang version 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec746213857d083c0e8b0abb568790) (https://android.googlesource.com/toolchain/llvm 7a6618d69e7e8111e1d49dc9e7813767c5ca756a) (based on LLVM 8.0.2svn)
```

Can you confirm that this version doesn’t have the patch yet, or send more info on the clang issue so we can verify?

Also would there by any chance be a workaround for this on the runtime side? We’d like to use the 2.0 ABI if at all possible, and the Android clang version seems to contain some customizations that would make it at least tricky to update to a newer version without waiting for Google to update the NDK.

Thanks!

**Comment by davidchisnall** [comment]
I don't know what that corresponds to in upstream LLVM.  8.0 isn't out yet (it's in RC4), so something that claims to be based on 8.0.2 is from the future.  I think this is the fix you need:

https://github.com/llvm/llvm-project/commit/386477a54137833a4ecd713b950346e3fb605315#diff-3e7a634dcc44462cc5f70470bfa7a23e

**Comment by triplef** [comment]
Thanks for the info! I’ve been unable to confirm which official LLVM version the NDK release is based on (they unfortunately seem to be misaligned in version numbers), but their [master branch](https://android.googlesource.com/toolchain/clang/+/refs/heads/master) [contains your fix](https://android.googlesource.com/toolchain/clang/+/bd0803d06773d50b43983536115a664590980800), so I am hopeful that the next release will have it.
