### ISSUE TITLE
objc_msgSend for ARM contains text relocations

### ISSUE THREAD

**Issue by triplef** [gnustep/libobjc2#92]
Text relocations are [no longer supported on Android](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#text-relocations-enforced-for-api-level-23) with API level >= 23, so libobjc2 can currently not be used on that platform due to text relocations in [objc_msgSend.arm.S](https://github.com/gnustep/libobjc2/blob/master/objc_msgSend.arm.S).

We’d love to see this fixed in the official release. My assembly knowledge is unfortunately lacking, but if there’s anything else we can do to make this happen (e.g. testing) please let me know. Thanks!

**Comment by triplef** [comment]
@davidchisnall I know you’ve been working with @gcasa on a [patch](https://github.com/gnustep/tools-android/blob/master/patches/libobjc2-arm-text-relocations.patch) for this, but unfortunately we found that it breaks support for small int classes.

**Comment by davidchisnall** [comment]
I need to set up an ARM emulator image to debug this on.  The fix is very simple, but quite fiddly.

**Comment by triplef** [comment]
Thanks. Feel free to get in touch if an actual device would make this easier, you can find my email in the git history. :)

**Comment by davidchisnall** [comment]
If you've got a device with clang and the libobjc2 sources installed that I can ssh into, that would be great.

**Comment by triplef** [comment]
We don’t have a way to set that up with public access, but we could probably sponsor you a device. Feel free to send me an email if that would help.

**Comment by triplef** [comment]
Thank you David! Much appreciated.

**Comment by davidchisnall** [comment]
Are you able to test the AArch64 version in #97?
