### ISSUE TITLE
objc_msgSend on AArch64 contains text relocations

### ISSUE THREAD

**Issue by davidchisnall** [gnustep/libobjc2#97]
Exactly the same problem as #92, but opening a separate issue to track the AArch64 version.

**Comment by davidchisnall** [comment]
I believe this should fix the issue:

```diff
--- a/objc_msgSend.aarch64.S
+++ b/objc_msgSend.aarch64.S
@@ -79,7 +79,8 @@
        ldp    \receiver, x8, [sp], #16
        br     x9
 6:
-       adr    x10, SmallObjectClasses
+       adrp   x10, :got:SmallObjectClasses
+       ldr    x10, [x10, :got_lo12:SmallObjectClasses]
        ldr    x9, [x10, x9, lsl #3]
        b      1b
        .cfi_endproc
```

@triplef, can you test this?

**Comment by triplef** [comment]
Thanks David – I can test this but I’m having some issues with our AArch64 builds right now that I need to figure out first...

**Comment by davidchisnall** [comment]
@triplef Ping?

**Comment by triplef** [comment]
I plan to look at this next week – apologies for the delay.

**Comment by triplef** [comment]
I tried the patch above, and it seems to work fine in my (somewhat limited) testing.

However, I also never saw a warning or error message about text relocations on AArch64, so I am wondering if either there was no text relocation to begin with, or text relocations are supported on that architecture.

**Comment by jordo** [comment]
The issue about text relocations on AArch64 I believe are more related to Android as a platform in particular, as we can't ship any library that contains text relocations, ( but in general on all platforms will be a  good thing to remove ).   I'm planning to test this on AArch64/Android in the next couple months

**Comment by triplef** [comment]
I should clarify that my comment about the missing warning was based on the fact that Android *did* show a warning/error about text relocations for objc_msgSend on 32-bit arm (runtime log if targeting < API level 23, or linker error if targeting >= 23), so I would have expected one on arm64 as well.

**Comment by davidchisnall** [comment]
Rereading the original assembly, I don't think we should have had a text relocation there either, though we might have had linker failures if the variable ended up too far away from the binary (unlikely - libobjc2 is small!).  I'll close this for now, but feel free to reopen it if you see errors on 64-bit Android.
